### PR TITLE
[WIP] Theme guessing frontend

### PR DESCRIPTION
**Pull request by rossjones**
Still requires....

1. Constraining to publishers
2. Post PR #71 
3. Post PR #70 
4. Additions to the data returned by theme-guessing.

### CODE REVIEW

**Comment by davidread** [comment]
This is very close. All it needs is for the 'reasons' to be displayed when you press "Update" on the form. @morty could you polish that off?

**Comment by morty** [comment]
@davidread I think this is good to go now. It's merged in on the staging server. Let me know what you think...

**Comment by davidread** [comment]
This is great. Couple of thoughts.

When you click to reveal the tags, then you might miss that section appearing. How about the page scrolls down to that section, with a named anchor?

"Otherwise please contact us" - how about "Otherwise please contact us with suggested keywords to associate with a particular theme.". I also suggest a new category "theming" on the contact form, which you can preselect with a URL parameter, and it'd probably be helpful to add another URL parameter to fill the subject field with "Theming dataset {{dataset_url}}".

This one fails with a 400 error. I guess it's to do with encoding.
http://co-prod2.dh.bytemark.co.uk/dataset/edit/england-nhs-connecting-for-health-organisation-data-service-data-files-of-general-medical-practices#tab-description

**Comment by morty** [comment]
@davidread He's a screenshot of the message about what to do if the theme is wrong.

theme-info

Let me know what you think.

**Comment by davidread** [comment]
Yes that's great to have the colour. However red means error in our colour scheme. I suggest v. light green background. And maybe preface the message with 'Note:'.

BTW the button also needs changing from blue to green, like the other buttons.

**Comment by morty** [comment]
Better? 

theme-info2

**Comment by davidread** [comment]
Yes, cool. I'll merge and deploy.

**Comment by davidread** [comment]
This is live now, all good.

**Pull request merged**
