### PR TITLE
Fix format autocomplete

### LINKED ISSUE #342: format autocomplete is broken for timeseries resources
Also broken when you add a new row for single file resources.

### PR DESCRIPTION
**Pull request by morty**
Fixes #342

### CODE REVIEW

**Comment by davidread** [comment]
Please do deploy

**Comment by davidread** [comment]
BTW I also merged 342-broken-format-autocomplete into spatial-ol3-integration but it is slightly different and if I now merge master into it I get this conflict:
```
206     /* Resource format autocomplete */
207     $(document).on('keydown.autocomplete', function(){
208 <<<<<<< HEAD
209       $('.format-typeahead').autocomplete({lookup: DGU_RESOURCE_FORMATS,
210                                            lookupLimit: 5,
211                                            triggerSelectOnValidInput: false});
212 =======
213       $('.format-typeahead').autocomplete({source: DGU_RESOURCE_FORMATS, items:5});
214 >>>>>>> 3c3ad8996fc52e9775e42f019af32906f0d911dd
215     });
```

**Comment by morty** [comment]
I have deployed now. On that branch you want the top bit. It's only conflicting because of the indent change.

**Comment by davidread** [comment]
Thanks @morty

**Pull request merged**
