### PR TITLE
Themes stored in long form

### PR DESCRIPTION
**Pull request by morty**

### CODE REVIEW

**Comment by davidread** [comment]
Reading through, this all looks great. Will test when you remove the WIP.

**Comment by morty** [comment]
Need to think how the theme search facet is affected. The facet uses the short form of the theme names.

It looks like the way `all_themes` is calculated in `plugin.py` is already broken for the secondary themes. It expects a space separated list when the theme-secondary is stored as a JSON list.

**Comment by davidread** [comment]
Deploy this after-hours, since the script takes 45 minutes, and during this time the dataset form appears without the theme (if it is one being changed) and the form won't save (the db table is locked during the 45 minute commit).

**Comment by davidread** [comment]
Ran on live.
```
(ckan)co@prod3 /vagrant/src/ckanext-dgu (master) $ python ckanext/dgu/bin/fix_themes.py $CKAN_INI --write
24012 datasets (active)
	Not fixing primary theme: 17029 [u'1-1-5m-scale-geology-through-climate-change-poster-map-covering-uk-mainland-northern-ireland-an', u'1-10-000-sealed-main-rivers', u'1-100-000...
	No secondary theme: 13613 [u'060-data-stats', u'1-class-settlement-morphology', u'1-in-1000yr-maximum-flood-depth', u'1-in-100yr-maximum-flood-depth', u'1-in-30-yr-maximu...
	Not fixing secondary theme: 7288 [u'04x-25k', u'05p-25k-july-13', u'05p-25k-june-2013', u'05p-over-25k-may', u'1-1-5m-scale-geology-through-climate-change-poster-map-covering-uk-...
	Fixing primary theme: 5869 [u'04x-25k', u'05p-25k-july-13', u'05p-25k-june-2013', u'05p-december-25k-expenditure', u'05p-over-25k-may', u'1-class-settlement-morphology', u'...
	Fixing secondary theme: 2780 [u'05p-december-25k-expenditure', u'1989-natural-history-museum-dorset-sites-only-macrobenthos-intertidal-survey-of-chalk-shores', u'1996-2013-no...
	No primary theme: 1114 [u'060-data-stats', u'1961-10-personal-data', u'2004_02_research-vessel-rv-loughfoyle-multibeam-data', u'2008-09-lennon-sales-data-download', u'2...
	Problem JSON: 331 [u'2013-14-member-allowances', u'afbi-botanical-monitoring-data-from-habitats-under-the-countryside-management-scheme-in-norther', u'afbi-marine-b...
	Error decoding JSON: 212 [u'accessibility-of-services-to-affordable-and-student-housing-provision', u'additional-affordable-dwellings', u'administrative-geography', u'admi...
	Time taken (h:m:s): 0:01:08.836885
```

**Pull request merged**
