### PR TITLE
Templates for ckanext-issues

### PR DESCRIPTION
**Pull request by rossjones**
The DGU styles don't match the issues onces, so this is intended to clean them up a little.
Also will need to remap the routes for publisher as they're hard-coded as organization in ckanext-issues.

### CODE REVIEW

**Comment by rossjones** [comment]
We are going to provide an option to restrict this to a single publisher for testing.

**Comment by rossjones** [comment]
I've disabled the UI in the relevant places, but the pages are still accessible if you know the URL.

**Comment by davidread** [comment]
This is has been closed incorrectly, due to it being moved to 'Done' in waffle. Maybe we should have a column for 'for merge' or something?

**Comment by rossjones** [comment]
Checking for errors in template wrt paging/ordering/sorting.

**Comment by davidread** [comment]
Info on installing this is in the dgu pad:
http://etherpad.co-dev1.dh.bytemark.co.uk/p/dgu
```
28/9/15 Issues integration install

cd /vagrant/src/ckanext-dgu; git pull  # branch issues-templates
grunt
cd /vagrant/src; git clone git@github.com:datagovuk/ckanext-issues.git
vim $CKAN_INI
  ckan.plugins += issues
  ckanext.issues.max_strikes = 2
  ckanext.issues.enabled_for_organizations = health-and-social-care-information-centre
  ckanext.issues.send_email_notifications = true
```

**Comment by davidread** [comment]
I've not looked through the moderation, so please look at that.

**Comment by davidread** [comment]
It might be called 'all issues' or something else public

**Comment by davidread** [comment]
We discussed showing the assigned user. To non-publishers it should say the dept of the user it is assigned to. There is (complex) code to do this, used in the history page - find the helper and use it. It's a DGU-only thing.

**Pull request merged**
