### PR TITLE
Allows publishers to be marked as closed (including jinjafication)

### PR DESCRIPTION
**Pull request by rossjones**
Adds a new schema field called closed which is used to denote a closed publisher.  The edit form has been jinjafied and now has a new checkbox which sets the closed state of the publisher.  

To get this to work we add a new version of the core CKAN boolean_validator that also allows the Missing value to be treated as false.

Also contains a replacement organisation (or several), and the message shown for closed orgs may need changing.  This is handled in the helper function get_closed_publisher_message()

### CODE REVIEW

**Comment by rossjones** [comment]
@davidread @morty I think this is probably ready for review now.

**Comment by davidread** [comment]
I'm just a bit concerned that this uses an extra, and your work on core ckan does it differently - I'd rather not start with divergence. Ideally you'd do it all in core and then we just use that.

**Comment by davidread** [comment]
PS I know this is just the way it worked out - more my indecision than anything. But is it reasonable to sort the core ckan one or would that be a stack more work?

**Comment by rossjones** [comment]
We could wait for the core one, but there's still a little indecision about how it would work. Can try and move some of this across though and see how we go.

**Pull request merged**
