### PR TITLE
[WIP] Prototype for a publisher select feature

### PR DESCRIPTION
**Pull request by morty**
Issue: https://github.com/datagovuk/ckanext-dgu/issues/315
Connects to #315

### CODE REVIEW

**Comment by davidread** [comment]
Looking good - styling is nice now. Remaining things:

Needs the abbreviations adding in.

And we don't want the selector to appear on the publisher page:
https://test.data.gov.uk/publisher/highways-agency

Anything else?

**Comment by davidread** [comment]
Would be good to get rid of the flicker on load

**Comment by rossjones** [comment]
Also worth noting that the boxes need to be inside the search form, because they're not links.  So that we don't end up generating URLs in JS it might be best to just extend the form down the page, which will make the mobile view a bit broken.  Also at some breakpoints when resizing the window, they overlap a bit.  This should be fixable.

**Comment by rossjones** [comment]
Finding issues in api calls and publisher controller where they are using fq which will need addressing.

**Comment by rossjones** [comment]
Fixed now.  We should move the fq conversion to ckanext-dgu and then delegate the rest of package_search back to core.

**Comment by rossjones** [comment]
Things that need tweaking:

* [ ] Missing facets: published/unpublished, NII, API
* [ ] Themes: only 10 of the 12 are there. I'd suggest we tell solr to get
12 items for every facet instead of 10.
* [ ] File formats: this is truncated, so perhaps do what we have for
publishers with top items and a full list
* [ ] Schema/Vocabulary need search/UK Location datasets is not available - Advanced options don't seem to show all items all the time.

**Comment by rossjones** [comment]
Changing the number of facet items shown can be done as follows in $CKAN_INI

```
search.facets.default = 20
```

but this is for all facets, not per-facet :(

**Comment by rossjones** [comment]
Work out why abbreviations aren't working until (most relevant) publisher is selected, and should be gtg.

**Pull request closed without merging**
