### PR TITLE
Added keywords for better theme classification

### PR DESCRIPTION
**Pull request by morty**
Based on machine learning analysis of the description and theme of all of the existing datasets.

### CODE REVIEW

**Comment by davidread** [comment]
Great! Please do deploy.

And categorize any uncategorized datasets - hopefully we'll catch a few more. I think my themes command (ckanext-dgu/ckanext/dgu/bin/theme.py categorize) does that - try it locally first to check it is being sensible.

**Comment by morty** [comment]
I've deployed the updated keywords. 

Running the categorize script (on dev) it looks like it's giving themes to unpublished datasets. Is that expected/wanted?

**Comment by davidread** [comment]
yes, 'unpublished datasets' should have a theme

**Comment by morty** [comment]
OK, I've run the categorization script now.

**Comment by davidread** [comment]
Great :)

I imagine the results were similar to what I get locally:
```
$ python ../ckanext-dgu/ckanext/dgu/bin/theme.py $CKAN_INI categorize
Categorize summary:
	No match: 1077 [u'060-data-stats', u'1961-10-personal-data', u'2004_02_research-vessel-rv-loughfoyle-multibeam-data', u'2008-09-lennon-sales-data-download', u'access-to-information-toolkit-ait', u'accessions', u'actions-from-european-social-fund-quarterly-review-spreadsheet', u'ad-hoc-research-studies-15-20-quantitative-studies-per-year', u'advice-notes-on-curating-time-based-media-such-as-film-audio-etc--creative-commons', u'aed-manpower-tracker', u'aerial-photography-data', u'afcc-trg-year-11-12', u'afcc-trg-year-11-13', u'afcc-trg-year-11-14', u'affordable-homes-guarantees-programme', u'ai-media-spotlight', u'ainc-ii-r', u'allowance-database', u'alumni-association-records', u'alumni-database-for-future-international-leaders-programme-_1', u'amenity-greenspace-buffer', u'amenity-greenspace1', u'amsurv--antimocrobial-resistance-data-from-nhs-labs', u'analytical-methods-in-feedstuffs', u'ancillary-costs-survey-acs', u'annual-accounts_2', u'annual-leave-reports_1', u'annual-monitoring-update-on-t...
	Theme where there was none previously: 255 [u'2011-sub-regional-data guess=Society 3', u'access-control-system guess=Government 12', u'analysis_of_milk_selling_arrangements_on_dairy_farms_in_england_2008-09 guess=Business & Economy 5', u'area-of-special-control-of-advertisements guess=Towns & Cities 4', u'audit-of-practice-data-for-the-second-round-of-the-national-audit-of-schizoprhenia-england-only guess=Government 8', u'avon-wiltshire-nhs-trust-over-25k-expenditure-august-2014 guess=Government Spending 16', u'balanced-scorecard-_1 guess=Government 2', u'better-data-for-corporation-tax-bdct guess=Government 1', u'budget-data-system guess=Government 3', u'budget-information guess=Government 6', u'budget-management guess=Government 4', u'budget-monitor--divisional-finance-officer-dfo-portal guess=Government 4', u'building-energy-efficiency-survey-main guess=Towns & Cities 8', u'building-for-life-local-authority-assessors-2010 guess=Government 12', u'cabinet-office-spending-approvals guess=Government Spending 4', u'cambridges...
	Time taken (h:m:s): 0:00:13.081505
```
i.e. an extra 250 have a theme, but 1000 still don't have one. They look like odds and sods.

**Pull request merged**
